In [22]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import LabelEncoder
import utils

In [14]:
df = pd.read_csv('meteo_paris.csv')
df

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,paris,2020-09-01,21.4,11.5,16.1,21.4,11.5,16.1,8.7,63.5,...,13.9,6,NaN,2020-09-01T07:07:47,2020-09-01T20:32:17,0.47,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"07149099999,07156099999,07146099999,0715709999..."
1,paris,2020-09-02,22.0,11.2,16.8,22.0,11.2,16.8,7.7,57.3,...,17.9,8,NaN,2020-09-02T07:09:12,2020-09-02T20:30:14,0.50,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"07149099999,07156099999,07146099999,0715709999..."
2,paris,2020-09-03,26.9,15.3,21.3,26.7,15.3,21.3,10.8,52.2,...,14.9,6,NaN,2020-09-03T07:10:37,2020-09-03T20:28:10,0.54,Overcast,Cloudy skies throughout the day.,cloudy,"07149099999,07156099999,07146099999,0714509999..."
3,paris,2020-09-04,28.6,18.1,23.2,27.6,18.1,23.0,13.0,55.4,...,18.8,7,NaN,2020-09-04T07:12:01,2020-09-04T20:26:05,0.57,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"07149099999,07156099999,07146099999,0715709999..."
4,paris,2020-09-05,20.1,15.4,17.7,20.1,15.4,17.7,10.6,65.0,...,11.5,6,NaN,2020-09-05T07:13:26,2020-09-05T20:24:01,0.60,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,"07149099999,07156099999,07146099999,0714509999..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,paris,2021-09-05,29.3,18.2,22.5,29.7,18.2,22.5,16.8,72.3,...,18.1,7,NaN,2021-09-05T07:13:06,2021-09-05T20:24:31,0.95,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"07149099999,07156099999,07146099999,0714509999..."
370,paris,2021-09-06,29.5,17.4,23.5,29.2,17.4,23.4,14.0,57.2,...,17.9,7,NaN,2021-09-06T07:14:31,2021-09-06T20:22:26,0.98,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"07149099999,07156099999,07146099999,E3042,0715..."
371,paris,2021-09-07,29.6,16.6,23.3,28.5,16.6,23.1,11.8,50.4,...,18.1,7,NaN,2021-09-07T07:15:56,2021-09-07T20:20:21,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"07149099999,07156099999,07146099999,E3042,0715..."
372,paris,2021-09-08,30.2,17.4,23.4,30.5,17.4,23.5,14.2,57.1,...,17.2,6,NaN,2021-09-08T07:17:21,2021-09-08T20:18:15,0.05,"Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,rain,"07149099999,07156099999,07146099999,E3042,0715..."
373,paris,2021-09-09,26.3,19.8,22.1,26.3,19.8,22.1,18.0,79.3,...,10.6,6,NaN,2021-09-09T07:18:46,2021-09-09T20:16:08,0.09,"Rain, Overcast",Cloudy skies throughout the day with rain.,rain,"07149099999,07156099999,07146099999,0714509999..."

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              374 non-null    object
 1   datetime          374 non-null    object
 2   tempmax           374 non-null    float64
 3   tempmin           374 non-null    float64
 4   temp              374 non-null    float64
 5   feelslikemax      374 non-null    float64
 6   feelslikemin      374 non-null    float64
 7   feelslike         374 non-null    float64
 8   dew               374 non-null    float64
 9   humidity          374 non-null    float64
 10  precip            374 non-null    float64
 11  precipprob        374 non-null    int64
 12  precipcover       374 non-null    float64
 13  preciptype        240 non-null    object
 14  snow              374 non-null    int64
 15  snowdepth         374 non-null    float64
 16  windgust          372 non-null    float64
 17  windspeed         374 non-null    float64
 18  winddir           374 non-null    float64
 19  sealevelpressure  372 non-null    float64
 20  cloudcover        374 non-null    float64
 21  visibility        374 non-null    float64
 22  solarradiation    374 non-null    float64
 23  solarenergy       374 non-null    float64
 24  uvindex           374 non-null    int64
 25  severerisk        0 non-null      float64
 26  sunrise           374 non-null    object
 27  sunset            374 non-null    object
 28  moonphase         374 non-null    float64
 29  conditions        374 non-null    object
 30  description       374 non-null    object
 31  icon              374 non-null    object
 32  stations          374 non-null    object
dtypes: float64(21), int64(3), object(9)
memory usage: 96.6+ KB

In [42]:
columns_to_keep = ['datetime', 'temp', 'precip', 'windspeed', 'visibility']
df_n = df[columns_to_keep]
df_n.head()

     datetime  temp  precip  windspeed  visibility
0  2020-09-01  16.1   0.000       13.6        25.1
1  2020-09-02  16.8   0.000       11.1        24.1
2  2020-09-03  21.3   0.000       17.2        25.6
3  2020-09-04  23.2   0.000       15.8        25.4
4  2020-09-05  17.7   0.016       18.3        25.0

In [43]:
df_n.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    374 non-null    object
 1   temp        374 non-null    float64
 2   precip      374 non-null    float64
 3   windspeed   374 non-null    float64
 4   visibility  374 non-null    float64
dtypes: float64(4), object(1)
memory usage: 14.7+ KB

In [44]:
df_n.nunique()

datetime      374
temp          180
precip        192
windspeed     177
visibility    137
dtype: int64

In [45]:
df['icon'].unique()

array(['partly-cloudy-day', 'cloudy', 'rain', 'clear-day', 'snow'],
      dtype=object)

In [51]:
mapping = {'snow': 0, 'rain': 1, 'cloudy': 2, 'partly-cloudy-day': 3, 'clear-day': 4}
df_n.loc[:, 'icon_encoded'] = df['icon'].map(mapping)

/var/folders/rx/rlnnk9hd4dbfg0t2drhsrvyw0000gn/T/ipykernel_25261/3135373508.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_n.loc[:, 'icon_encoded'] = df['icon'].map(mapping)

In [52]:
df_n.head()

     datetime  temp  precip  windspeed  visibility  icon_encoded
0  2020-09-01  16.1   0.000       13.6        25.1             3
1  2020-09-02  16.8   0.000       11.1        24.1             3
2  2020-09-03  21.3   0.000       17.2        25.6             2
3  2020-09-04  23.2   0.000       15.8        25.4             3
4  2020-09-05  17.7   0.016       18.3        25.0             1